---
- name: Disable the setup utility
  bigip_sys_global:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    gui_setup: "disabled"
  delegate_to: localhost
...
